// src/soldiers.js
export const soldiers = [
  {
    id: 1,
    name: "Captain Vikram Batra",
    rank: "Captain",
    regiment: "13 JAK RIF",
    war: "Kargil War (1999)",
    award: "Param Vir Chakra",
    image: "./public/vikram-batra.jpg", // Wiki Commons
    desc: "Known as 'Sher Shah', his famous signal during the capture of Point 5140 was 'Yeh Dil Maange More'."
  },
  {
    id: 2,
    name: "Major Sandeep Unnikrishnan",
    rank: "Major",
    regiment: "7 Bihar / NSG",
    war: "Operation Black Tornado (2008)",
    award: "Ashoka Chakra",
    image: "./public/sandeep-unni.jpg", // Wiki Commons
    desc: "Led the commando operation at Taj Hotel. His last words were 'Do not come up, I will handle them.'"
  },
  {
    id: 3,
    name: "Major Shaitan Singh",
    rank: "Major",
    regiment: "13 Kumaon",
    war: "Sino-Indian War (1962)",
    award: "Param Vir Chakra",
    image: "/shaitan_S.jpg",
    desc: "Led the 'Charlie Company' at Rezang La. Fighting with only 120 men against 1000s, he refused to retreat and fought till the last man.",
  },
  {
    id: 4,
    name: "Captain Tushar Mahajan",
    rank: "Captain",
    regiment: "9 Para (Special Forces)",
    war: "Pampore Operation (2016)",
    award: "Shaurya Chakra",
    image: "tushar_m.jpg", 
    desc: "Eliminated a terrorist in close quarters at the EDI building to save his subordinates, sacrificing his life in the process.",
  },
  {
    id: 5,
    name: "Major Somnath Sharma",
    rank: "Major",
    regiment: "4 Kumaon",
    war: "Indo-Pak War (1947)",
    award: "Param Vir Chakra",
    image: "somnath_s.jpg",
    desc: "The first recipient of the PVC. His last message was: 'The enemy is only 50 yards from us... I shall not withdraw an inch but will fight to our last man and our last round.'",
  },
  {
    id: 6,
    name: "CQMH Abdul Hamid",
    rank: "Company Quarter Master Havildar",
    regiment: "4 Grenadiers",
    war: "Indo-Pak War (1965)",
    award: "Param Vir Chakra",
    image: "abdul_h.jpg",
    desc: "In the Battle of Asal Uttar, he single-handedly destroyed 7 Pakistani Patton tanks using a jeep-mounted recoilless gun.",
  },
  {
    id: 7,
    name: "Yogendra Singh Yadav",
    rank: "Grenadier (Retd. Subedar Major)",
    regiment: "18 Grenadiers",
    war: "Kargil War (1999)",
    award: "Param Vir Chakra",
    image: "yogendra_s.jpg",
    desc: "The youngest PVC recipient. He climbed the vertical cliff of Tiger Hill. Despite taking 15 bullets, he crawled forward to destroy enemy bunkers.",
  },
  {
    id: 8,
    name: "Paratrooper Chhatrapal Singh",
    rank: "Paratrooper",
    regiment: "9 Para (Special Forces)",
    war: "Operation Rakshak (2020)",
    award: "Kirti Chakra",
    image: "cps.jpg", // Placeholder image (Medal ribbon) as high-quality public photo is rare
    desc: "Displayed exceptional bravery during an anti-terrorist operation in Kashmir, holding off terrorists to ensure the safety of his squad.",
  },
  {
    id: 9,
    name: "Major Mohit Sharma",
    rank: "Major",
    regiment: "1 Para (Special Forces)",
    war: "Op Rakshak - Kupwara (2009)",
    award: "Ashoka Chakra",
    image: "mohit-sharma.jpg",
    desc: "Infiltrated Hizbul Mujahideen under the alias 'Iftikhar'. In his final battle, he killed 4 terrorists despite grave injuries to save his team.",
  },
  {
    id: 10,
    name: "Captain Vijayant Thapar",
    rank: "Captain",
    regiment: "2 Rajputana Rifles",
    war: "Kargil War (1999)",
    award: "Vir Chakra",
    image: "v_thapar.jpg",
    desc: "Captured the Knoll in the Battle of Tololing. His final letter to his family said, 'By the time you get this, I will be observing you from the sky.'",
  },
  {
    id: 11,
    name: "Captain Pawan Kumar",
    rank: "Captain",
    regiment: "10 Para (Special Forces)",
    war: "Pampore Operation (2016)",
    award: "Shaurya Chakra",
    image: "pawan_kumar.jpg",
    desc: "Led his men into the EDI building against terrorists. His famous quote: 'Kisiko reservation chahiye... humein bas apni razai (flag) chahiye.'",
  },

  // --- KARGIL WAR LEGENDS ---
  {
    id: 12,
    name: "Captain Manoj Kumar Pandey",
    rank: "Captain",
    regiment: "1/11 Gorkha Rifles",
    war: "Kargil War (1999)",
    award: "Param Vir Chakra",
    image: "/manoj_k.jpg",
    desc: "Led the capture of Jubar Top. Despite being wounded, he destroyed 4 bunkers. His final words: 'Na chodnu' (Don't spare them).",
  },
  {
    id: 13,
    name: "Rifleman Sanjay Kumar",
    rank: "Rifleman (now Subedar Major)",
    regiment: "13 JAK RIF",
    war: "Kargil War (1999)",
    award: "Param Vir Chakra",
    image: "sanjay_kumar.jpg",
    desc: "Captured Area Flat Top. He ran out of ammo, picked up an enemy machine gun, and killed the remaining intruders in hand-to-hand combat.",
  },

  // --- 1971 INDO-PAK WAR HEROES ---
  {
    id: 14,
    name: "2nd Lt Arun Khetarpal",
    rank: "Second Lieutenant",
    regiment: "17 Poona Horse",
    war: "Indo-Pak War (1971)",
    award: "Param Vir Chakra",
    image: "/arun-k.jpg",
    desc: "The 'Tank Destroyer' of Basantar. At age 21, he destroyed 10 enemy tanks. His last radio message: 'No sir, I will not abandon my tank. My gun is still working.'",
  },
  {
    id: 15,
    name: "Lance Naik Albert Ekka",
    rank: "Lance Naik",
    regiment: "14 Guards",
    war: "Indo-Pak War (1971)",
    award: "Param Vir Chakra",
    image: "albert_ekka.jpg",
    desc: "During the Battle of Gangasagar, he silenced two enemy machine guns and bayoneted an enemy soldier, ensuring the fall of a key Pakistani fortress.",
  },

  // --- 1962 SINO-INDIAN WAR HEROES ---
  {
    id: 16,
    name: "Subedar Joginder Singh",
    rank: "Subedar",
    regiment: "1 Sikh",
    war: "Sino-Indian War (1962)",
    award: "Param Vir Chakra",
    image: "joginder_singh.jpg",
    desc: "At Bum La, he led his platoon against three waves of Chinese attacks. When ammo ran out, he led a bayonet charge shouting 'Jo Bole So Nihal, Sat Sri Akal'.",
  },
  {
    id: 17,
    name: "Major Dhan Singh Thapa",
    rank: "Major",
    regiment: "1/8 Gorkha Rifles",
    war: "Sino-Indian War (1962)",
    award: "Param Vir Chakra",
    image: "dhan_s_t.jpg",
    desc: "Commanded a post at Pangong Lake (Ladakh). He was believed dead after fighting off multiple Chinese waves, but was later found alive as a POW.",
  }
];